[versions]
agp = "8.12.1"
android-compileSdk = "36"
android-minSdk = "29"
android-targetSdk = "35"
androidx-activity = "1.10.1"
androidx-lifecycle = "2.9.2"
androidx-testExt = "1.3.0"
cmpcharts = "2.0.6"
composeMultiplatform = "1.8.2"
junit = "4.13.2"
kableCore = "0.40.0"
kotlin = "2.2.10"
kotlin-serialization = "1.9.0"
kotlinxDatetime = "0.7.1"
ktor = "3.2.3"
compose-material3 = "1.9.0-beta03"
compose = "1.8.2"
compose-ui-tooling = "1.8.2"
compose-ui-tooling-preview = "1.8.2"
lifecycleViewModel = "2.9.2"
materialIconsCore = "1.7.3"
navigationCompose = "2.9.0-beta05"
moko = "0.19.0"
okio = "3.16.0"
permissionsCompose = "0.20.0"
haptics = "0.2.5"

[libraries]
cmpcharts = { module = "network.chaintech:cmpcharts", version.ref = "cmpcharts" }
kable-core = { module = "com.juul.kable:kable-core", version.ref = "kableCore" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "compose-ui-tooling" }
compose-ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose-ui-tooling-preview" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "compose-material3" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization-json-okio = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json-okio", version.ref = "kotlin-serialization" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
kotlin-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-serialization" }
material-icons-core = { module = "org.jetbrains.compose.material:material-icons-core", version.ref = "materialIconsCore" }
navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycleViewModel" }
moko-permissions-compose = { module = "dev.icerock.moko:permissions-compose", version.ref = "permissionsCompose" }
moko-permissions = { module = "dev.icerock.moko:permissions", version.ref = "permissionsCompose" }
moko-permissions-bluetooth = { module = "dev.icerock.moko:permissions-bluetooth", version.ref = "permissionsCompose" }
moko-permissions-location = { module = "dev.icerock.moko:permissions-location", version.ref = "permissionsCompose" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
lexilabs-basic-haptic = { module = "app.lexilabs.basic:basic-haptic", version.ref = "haptics"}

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization-plugin = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
